//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string WhatsAppMessage { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public Nullable<System.DateTime> MessageSentDate { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
    }
}
