//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int RollNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Trainer Trainer { get; set; }
        public virtual Course Course { get; set; }
    }
}
